services:
  db:
    image: postgres:15.2-alpine
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=synci-db"
    ports:
      - "5432:5432"
    volumes:
      - db.data:/var/lib/postgresql/data
volumes:
  db.data:
