services:
  frontend:
    container_name: synci-frontend
    platform: linux/amd64
    image: synci-frontend:latest
    ports:
      - "5173:5173"
    networks:
      - default 

  backend:
    container_name: synci-backend
    platform: linux/amd64 # adding a plattform causes gradle build to timeout with no error
    image: synci-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - default 
      - database

  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=synci-db"
    volumes:
      - db.data:/var/lib/postgresql/data
    networks:
      - database


volumes:
  db.data:

networks:
  database:
    name: 'database'
