version: '3.8'
services:
  db:
    ports:
      - '5432:5432'
  frontend:
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/
    image: synci-frontend-local
    build:
      context: ./frontend
    container_name: "synci-frontend-${STAGE:-local}"
    platform: linux/amd64