name: "synci_instance_dev"

services:
  frontend:
    container_name: "synci-frontend-dev"
    platform: linux/amd64
    image: ghcr.io/andriwild/synci/frontend:latest
    environment:
      - VITE_STAGE=dev
      - VITE_BACKEND_URL=https://dev.synci.awild.ch
    ports:
      - 5173:5173
    networks:
        synci-net:
          aliases:
            - synci-net-frontend-dev

  backend:
    container_name: "synci-backend-dev"
    platform: linux/amd64 # adding a plattform causes gradle build to timeout with no error
    image: ghcr.io/andriwild/synci/backend:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - DB_HOST=database-net-db-dev
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
        synci-net:
          aliases:
            - synci-net-backend-dev
        database:
          aliases:
            - database-net-backend-dev

  db:
    container_name: "synci-db-dev"
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    volumes:
      - db.data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
        synci-net:
          aliases:
            - synci-net-db-dev
        database:
          aliases:
            - database-net-db-dev


volumes:
  db.data:

networks:
  database:
    name: 'database-dev'

  synci-net:
    name: 'synci-net-dev'
