{
 "title": "Synci",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Caddy Upstreams",
   "type": "status-history",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "caddy_reverse_proxy_upstreams_healthy{}",
     "legendFormat": "{{upstream}}"
    }
   ]
  },
  {
   "title": "Requests on calendar/subscribe/{id}",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{uri=\"/calendar/subscribe/{configId}\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Response Code",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "increase(caddy_http_request_duration_seconds_count{}[1m])",
     "legendFormat": "{{method}}: {{code}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=\"$instance\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=\"$instance\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 11 },
   "targets": [
    {
     "expr": "system_cpu_count{instance=\"$instance\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_load_average_1m{instance=\"$instance\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  }
 ]
}