### get all syncconfigs - store the first returnd config id in mySyncId

GET {{backendUrl}}/syncconfigs
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth0-oauth")}}

> {%
    const id = response.body.body[0].id;
    client.global.set("mySyncId", id);
    client.log("ID: " + id);
%}


### get a single syncconfig

GET {{backendUrl}}/syncconfigs/{{mySyncId}}
Authorization: Bearer {{$auth.token("auth0-oauth")}}


### create a new sync config

POST {{backendUrl}}/syncconfigs
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth0-oauth")}}

{
  "id": "e2b7a8f0-9f3e-11eb-a8b3-0242ac830003",
  "name": "SampleConfig",
  "events": [
    { "id": "e2d06a51-4bcc-4822-a2f2-97686f32b128", "sourceId": 2 },
    { "id": "1803641", "sourceId": 3 }
  ],
  "teams": [
    { "id": "14099", "sourceId": 3 }
  ],
  "sports": [ "225ffb58-e4ae-4c50-804a-843d9bf5d098" ]
}


### subscribe calendar

GET {{backendUrl}}/calendars/{{mySyncId}}/subscribe
Authorization: Bearer {{$auth.token("auth0-oauth")}}


### get sport id

GET {{backendUrl}}/sports
Authorization: Bearer {{$auth.token("auth0-oauth")}}

> {%
    const sportId = response.body.body[2].id;
    client.global.set("sportId", sportId);
    client.log("ID: " + sportId);
%}


### sports by id

GET {{backendUrl}}/sports/{{sportId}}/teams?pageSize=5&page=0
Authorization: Bearer {{$auth.token("auth0-oauth")}}