### Create Team Calendar
http://localhost:8080/api/create-calendar/10192


### Get Fotmob League Overview
https://www.fotmob.com/api/leagues?id=69&tab=overview&type=league


### Get Fotmob Config
http://localhost:8080/api/fotmob/config


### All Fotmob Leagues
https://www.fotmob.com/api/allLeagues
