ch:
  boosters:
    db:
      jdbcUrl: jdbc:postgresql://database-net-db-local:5432/synci-db
spring:
  security:
    oauth2:
      client:
        provider:
          synci-keycloak:
            issuer-uri: http://localhost:8090/realms/synci
        registration:
          keycloak:
            provider: synci-keycloak
            client-id: synci-backend
            client-secret: qsRBHYpRSoqE5XrCCQE1iM6BqdK66tDK
            authorization-grant-type: authorization_code
            scope:
              - openid