ch:
  boosters:
    db:
      jdbcUrl: jdbc:postgresql://localhost:5432/synci-dbspring:
  security:
    oauth2:
      client:
        provider:
          synci-keycloak:
            issuer-uri: http://localhost:8090/realms/synci
        registration:
          keycloak:
            provider: synci-keycloak
            client-id: synci-backend
            client-secret: PsAbJk9P2jXJI07eykbUSTWUWD6TDslt
            authorization-grant-type: authorization_code
            scope:
              - openid