global:
  scrape_interval: 5s

scrape_configs:
  - job_name: caddy
    static_configs:
      - targets: ['caddy:2019']
  - job_name: spring
    static_configs:
      - targets: ["synci-backend-dev:8080", "synci-backend-prod:8080"]
    metrics_path: '/api/actuator/prometheus'
