global:
  scrape_interval: 5s

scrape_configs:
  - job_name: caddy
    static_configs:
      - targets: ['host.docker.internal:2019']
  - job_name: spring
    static_configs:
      - targets: ["host.docker.internal:8080", "host.docker.internal:8081"]
    metrics_path: '/api/actuator/prometheus'
