name: prod deploy

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    name: Deploy to prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Create docker context
        run: |
          docker context create remote --docker "host=ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}"
          docker context use remote

      - name: Log into registry
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }} ${{ env.REGISTRY }}

      - name: Deploy to remote server
        run: |
          docker compose -p prod -f docker-compose.prod.yml stop
          docker compose -p prod -f docker-compose.prod.yml rm -f
          docker compose -p prod -f docker-compose.prod.yml pull
          docker compose -p prod -f docker-compose.prod.yml up -d --force-recreate
