name: dev build and push

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  VERSION: ${{ github.ref_name }}

jobs:
  build_backend:
    name: Build backend
    runs-on: ubuntu-latest

    steps:
      - name: Start PostgreSQL service
        run: |
          sudo systemctl start postgresql.service
          pg_isready

      - name: Update db user
        run: |
          sudo -u postgres psql --command="ALTER USER postgres WITH PASSWORD 'postgres'"

      - name: Create synci database
        run: |
          sudo -u postgres psql --command='CREATE DATABASE "synci-db" OWNER postgres;'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build backend image 
        run: |
          docker build --network="host" -t ${{ env.REGISTRY }}/${{ github.repository }}/backend:${{ env.VERSION }} ./backend

      - name: Push backend image
        run: |
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/backend:${{ env.VERSION }}
     

  build_frontend:
    name: Build frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build frontend image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ github.repository }}/frontend:${{ env.VERSION }} ./frontend

      - name: Push frontend image
        run: |
          docker push ${{ env.REGISTRY }}/${{ github.repository }}/frontend:${{ env.VERSION }}
          
  deploy:
    name: Deploy frontend and backend
    needs: [build_backend, build_frontend]
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup SSH
        run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Create docker context
        run: |
            docker context create remote --docker "host=ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}"
            docker context use remote

      - name: Log into registry
        run: |
            docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }} ${{ env.REGISTRY }}

      - name: Deploy to remote server
        env:
          STAGE:                ${{ vars.STAGE }}
          POSTGRES_DB_NAME:     ${{ vars.POSTGRES_DB_NAME }}
          POSTGRES_USER:        ${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD:    ${{ secrets.POSTGRES_PASSWORD }}
          VITE_STAGE:           ${{ vars.STAGE }}
          VITE_BACKEND_URL:     ${{ vars.VITE_BACKEND_URL }}
          VITE_BACKEND_HOST:    ${{ vars.VITE_BACKEND_HOST }}
          VITE_AUTH0_DOMAIN:    ${{ vars.VITE_AUTH0_DOMAIN }}
          VITE_AUTH0_CLIENT_ID: ${{ vars.VITE_AUTH0_CLIENT_ID }}
          BACKEND_PORT:         ${{ vars.BACKEND_PORT }}
          FRONTEND_PORT:        ${{ vars.FRONTEND_PORT }}
          VERSION:              ${{ env.VERSION }}
          REGISTRY:             ${{ env.REGISTRY }}
          REPOSITORY:           ${{ github.repository }}
        run: |
            docker compose -p dev -f docker-compose.yml stop
            docker compose -p dev -f docker-compose.yml rm -f
            docker compose -p dev -f docker-compose.yml pull
            docker compose -p dev -f docker-compose.yml up -d --force-recreate
