name: Dev Docker build and push

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  if: startsWith(github.ref, 'refs/tags/v')

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start PostgreSQL service
        run: |
          sudo systemctl start postgresql.service
          pg_isready

      - name: Update db user
        run: |
          sudo -u postgres psql --command="ALTER USER postgres WITH PASSWORD 'postgres'"

      - name: Create synci database
        run: |
          sudo -u postgres psql --command='CREATE DATABASE "synci-db" OWNER postgres;'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
     
      - name: Build frontend image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/synci-frontend:latest ./frontend

      - name: Push frontend image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/synci-frontend:latest
          
      - name: Build backend image 
        run: |
          docker build --network="host" --build-arg DB_HOST=localhost -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}/synci-backend:latest ./backend

      - name: Push backend image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}/synci-backend:latest

