name: infrastructure

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches: 
      - 'main' 
      - 'dev'
    paths: 
      - 'infrastructure/**'

env:
  REGISTRY: ghcr.io

jobs:

  deploy_infrastructure:
    name: Deploy infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Copy infrastructure to remote server
        run: |
          # Copy all files from infrastructure/ to synci/ on remote
          scp -r ./infrastructure/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:synci/

      - name: Deploy to remote server
        run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd synci && docker compose -p infra down && docker compose -p infra up -d --force-recreate"
