name: infrastructure

on:
  push:
    branches: ['main', 'dev']
    paths: ['infrastructure/**']


jobs:

  build_backend:
    name: Build backend
    runs-on: ubuntu-latest

    steps:
      - name: Start PostgreSQL service
        run: |
          echo "Starting infrastructure Pipline"
